export const RESIZABLE_NODE_MIN_WIDTH = 120;
export const RESIZABLE_NODE_MIN_HEIGHT = 120;

export const RESIZABLE_CYLINDER_NODE_MIN_WIDTH = 130;
export const RESIZABLE_CYLINDER_NODE_MIN_HEIGHT = 160;
